services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6380:6379'
    networks:
      - namviek-network

  storage:
    image: 'quay.io/minio/minio'
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - '9001:9001'
      - '9000:9000'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Admin@123
    volumes:
      - minio-data:/data
    networks:
      - namviek-network

  mongodb:
    image: 'mongo:latest'
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    ports:
      - '27017:27017'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    environment:
      - MONGO_INITDB_DATABASE=namviek
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - namviek-network

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        - ENV_FILE=.env
    image: namviek
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis:6379
      - MONGODB_URL=mongodb://mongodb:27017/namviek?replicaSet=rs0&authSource=admin&directConnection=true
      - AWS_MINIO_ENDPOINT=http://localhost:9000
    ports:
      - '3333:3000'
    command: /bin/sh -c "node ./main.js"
    healthcheck:
      test: curl --fail http://localhost:3333 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - mongodb
      - redis
      - storage
    networks:
      - namviek-network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    env_file:
      - .env
    ports:
      - '3005:3000'
    command: /bin/sh -c 'HOSTNAME="0.0.0.0" node ./apps/frontend/server.js'
    depends_on:
      - backend
    networks:
      - namviek-network

volumes:
  mongodb-data:
  minio-data:
  mongodb-config:

networks:
  namviek-network:
